// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIhO5hHC5OuZfhsy8No-4wr3sr2A3Grw',
    appId: '1:901358272329:web:0d8b93cc0c3fc4dd6d2498',
    messagingSenderId: '901358272329',
    projectId: 'ff14-frontline',
    authDomain: 'ff14-frontline.firebaseapp.com',
    storageBucket: 'ff14-frontline.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-SPNrSwppnpXDvyBlufgZxEAO37uXxpI',
    appId: '1:901358272329:android:41447b914a6536bd6d2498',
    messagingSenderId: '901358272329',
    projectId: 'ff14-frontline',
    storageBucket: 'ff14-frontline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcrNgu9qKmzofujS1UE7YKVc9b3UIuRc',
    appId: '1:901358272329:ios:dc89d95e9f0f23a06d2498',
    messagingSenderId: '901358272329',
    projectId: 'ff14-frontline',
    storageBucket: 'ff14-frontline.appspot.com',
    iosClientId: '901358272329-v64mik453on14o4l9i91rmnr632or1lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontline',
  );
}
